name: Continuous Integration
on: [push, pull_request, workflow_dispatch]
jobs:
  prettier:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn fmt:check
